### ISSUE TITLE
Tests using Spock Framework.

### ISSUE THREAD

**Issue by msgilligan** [dexX7/java-libbitcoinconsensus#1]
It would be nice to see some Spock Framework tests. I'm particularly interested in writing/learning tests that detail the operation of the Bitcoin scripts.

**Comment by dexX7** [comment]
Generally I agree, and I prefer Spock over JUnit, too. We should also add a lot of more tests.

My only concern would be the amount of new dependencies, but I'm open to it, especially because we can differentiate between test and non-test builds. Would you consider this as issue or relevant at all?

**Comment by msgilligan** [comment]
Look at the PR I just submitted. The changes to `build.gradle` are minimal and should not add dependencies to the generated JAR. There are many projects that use Spock, but are Java-only in terms of the code that ships in the JAR.  (BTW for bitcoinj-addons and OmniJ I'd actually like to remove the Groovy dependency from some of the JARs)

**Comment by dexX7** [comment]
This issue seems to be resolved via #5 and #8, but feel free to reopen, if needed.
