### ISSUE TITLE
Add to Bitcoin Core's list of example implementations

### ISSUE THREAD

**Issue by msgilligan** [dexX7/java-libbitcoinconsensus#9]
**java-libbitcoinconsensus** should be listed on [doc/shared-libraries.md](https://github.com/bitcoin/bitcoin/blob/master/doc/shared-libraries.md) in Bitcoin Core.

**Comment by dexX7** [comment]
Sure, but do you think it's ready?

**Comment by msgilligan** [comment]
It's ready to be an example implementation. ;) It's ready for people to start using/testing, isn't it? We can put any disclaimers we want on the project page (about being alpha, pre-alpha, etc.), but I would think we should make the project easy to find for those looking for a Java implementation. That way they can use it, report bugs and submit patches as necessary, rather than start a parallel implementation.

We should also announce it on the **bitcoinj** mailing list. I can send the message if you don't want to do it yourself.

**Comment by msgilligan** [comment]
Congrats, @dexX7 !

**Comment by msgilligan** [comment]
Do you want to announce it on the **bitcoinj** mailing list, or should I?

**Comment by dexX7** [comment]
Thanks, @msgilligan! Please go ahead with the mailing list post, if I'd like to. :)

**Comment by msgilligan** [comment]
> if I'd like to.

@dexX7 I'm not sure what you mean by the above.

**Comment by dexX7** [comment]
Ahh, sorry, ... I meant "you" of course! :)

It would be great, if you could post on the BitcoinJ mailing list, but only if you want to. :)

**Comment by msgilligan** [comment]
I want to. I had asked about it earlier, so I feel obligated to let people know. I'd also like to see some users and contributors :)

**Comment by dexX7** [comment]
Nice! Over the weekend I'm probably going to take a closer look at setting up Bintray.

**Comment by msgilligan** [comment]
You can definitely look at the Gradle scripts in **OmniJ** or **bitcoinj-addons**. Feel free to ask any questions or, if you'd like, I could even put together a PR.

**Comment by dexX7** [comment]
Thanks, help would be very appreciated! I was thinking about publishing to Bintray every release tag, and ideally the Groovy/JavaDoc would be published (e.g. to AWS S3), too. It looks like could be automated via Travis (see https://github.com/dexX7/java-libbitcoinconsensus/issues/12#issuecomment-142991966), but I haven't tested it yet. I'd later try to tackle it by creating a dummy/test repo and see how/if it works, but doing it manually would already be a step forward. :)

**Comment by msgilligan** [comment]
I'll set up the Gradle scripts for (manual) Bintray publishing this weekend.

Autopublishing to Bintray on a release tag is a great idea. I'd like to learn how to do it from Travis and/or Jenkins.

I would recommend publishing to Github pages over AWS S3 because it's free.

**Comment by msgilligan** [comment]
I sent a low-key announcement to the **bitcoinj** mailing list just now: https://groups.google.com/d/topic/bitcoinj/oZgCyo7UX2g/discussion

**Comment by dexX7** [comment]
Thanks @msgilligan, very appreciated!
